#!/bin/bash
exec 2>&1
export PIDFILE="/tmp/haproxy.pid"

reload() {
  echo "Reloading haproxy"
  if ! haproxy -c -f /marathon-lb/haproxy.cfg; then
    echo "Invalid config"
    return 1
  fi

  # Begin to drop SYN packets with firewall rules
  IFS=',' read -ra ADDR <<< "$PORTS"
  for i in "${ADDR[@]}"; do
    echo "ADDING RULE: iptables -w -I INPUT -p tcp --dport $i --syn -j DROP"
    iptables -w -I INPUT -p tcp --dport $i --syn -j DROP
  done

  # Wait to settle
  sleep 0.1

  # Save the current HAProxy state
  echo "SAVING HA PROXY STATE"
  socat /var/run/haproxy/socket - <<< "show servers state" > /var/state/haproxy/global

  # Trigger reload
  echo "TRIGGERING RELOAD"
  haproxy -p $PIDFILE -f /marathon-lb/haproxy.cfg -D -sf $(cat $PIDFILE)

  # Remove the firewall rules
  #IFS=',' read -ra ADDR <<< "$PORTS"
  #for i in "${ADDR[@]}"; do
  #  iptables -w -D INPUT -p tcp --dport $i --syn -j DROP
  #done
  echo "RESTORING IPTABLES"
  iptables -F INPUT
}

mkdir -p /var/state/haproxy
mkdir -p /var/run/haproxy

reload

trap reload SIGHUP
while true; do sleep 0.5; done
